# Generated by Django 4.2.9 on 2024-01-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=1024, verbose_name='room')),
                ('building', models.CharField(max_length=1024, verbose_name='building')),
                ('street', models.CharField(max_length=1024, verbose_name='street')),
                ('district', models.CharField(choices=[('CENTRAL', 'Central'), ('NEW_TERRITORIES', 'New Territories'), ('KWUN_TONG', 'Kwun Tong')], default='CENTRAL', max_length=30)),
            ],
            options={
                'db_table': 'T_address',
            },
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=32)),
                ('doctor_category', models.CharField(choices=[('GENERAL_PRACITIONER', 'General Pracitioner'), ('SPECIAL', 'Special')], default='GENERAL_PRACITIONER', max_length=20)),
                ('clinic_fee', models.IntegerField()),
                ('clinic_fee_remark', models.TextField()),
                ('member_discount_remark', models.TextField()),
                ('language', models.CharField(choices=[('ENG', 'Eng'), ('CHI', 'Chi')], default='ENG', max_length=5)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor_infos_app.address')),
            ],
            options={
                'db_table': 'T_doctor_info',
            },
        ),
        migrations.CreateModel(
            name='PhoneNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digits', models.CharField(max_length=8)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_nums', to='doctor_infos_app.doctorinfo')),
            ],
            options={
                'db_table': 'T_phone_num',
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('is_closed', models.BooleanField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='doctor_infos_app.doctorinfo')),
            ],
            options={
                'db_table': 'T_opening_hour',
            },
        ),
    ]
